package io.github.dalt1x.gerenciadorDeEventos.exception;

public class RecursoNaoEncontrado extends RuntimeException {
    public RecursoNaoEncontrado(String mensagem) {
        super(mensagem);
    }
}